### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by oofdere** [kvcmlive/website#21]
we don't have one

should work well at extremely low resolutions (16x16)

**Comment by BoscoBonetti** [comment]
Sorry, what is it we need here?

**Comment by oofdere** [comment]
> Sorry, what is it we need here?

Sorry for the lack of clarity, it's the small icon that gets displayed on the tabs.
![image](https://user-images.githubusercontent.com/43102807/85505016-2945ef80-b5a2-11ea-82a6-041fb384f010.png)

**Comment by BoscoBonetti** [comment]
Emailed.

**Comment by oofdere** [comment]
closed by #24
