### ISSUE TITLE
Distorted/ Bit Crush Audio on Android

### ISSUE THREAD

**Issue by olandaverde** [kvcmlive/website#23]
KVCM.Live on Android Phone. Audio drops lower than 8 bit. Desktop is fine. Checked on two different shows.

**Comment by oofdere** [comment]
Please provide more info:

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Comment by oofdere** [comment]
Works fine on my device, Note10+, Android 10, Samsung Internet 11.2.2.3.

@olandaverde could you please try to go to the Mixcloud website and try playing from there?

**Comment by olandaverde** [comment]
Windows 10. Google Chrome v83.

LG V20. Android 8. Chrome 83.0.4103.106

**Comment by oofdere** [comment]
Is it broken on both?

**Comment by olandaverde** [comment]
Sounds fine on my phone now. It was fine on desktop only, but for Lovey's show and my show, audio was bit crushed.

**Comment by oofdere** [comment]
Probably the 64k encoding on Mixcloud's end, then

**Comment by olandaverde** [comment]
I also thought it was the audio encoding (resampling) from OBS

**Comment by oofdere** [comment]
Probably not, unless misconfigured, id OBS was even used in the recording

**Comment by olandaverde** [comment]
Jason used Audition. I sent a cleanfeed channel for him to air
