### ISSUE TITLE
contact page

### ISSUE THREAD

**Issue by oofdere** [kvcmlive/website#27]
with social media buttons

**Comment by BoscoBonetti** [comment]
Also on that page should be:

KVCM Radio
Attn: Station Manager
5800 Fulton Ave.
Valley Glen, CA 91401

Phone: (818) 947-2305 Main Line
Email: KVCM@lavc.edu

**Comment by oofdere** [comment]
are we combining it with the about page?

**Comment by BoscoBonetti** [comment]
No, it will be:

ABOUT
About
Alumni 
History

CONTACT
Address, phone, email
Contact form
Social Media

**Comment by BoscoBonetti** [comment]
I know you're still working -- just a note. I love the icons and names in the sidebar. 

The more links we can make open in new tab on the website, the better.

**Comment by BoscoBonetti** [comment]
It looks fantastic so far.

Two things:
1. Attn: Station Manager should be on its own line beneath KVCM Radio.
2. The text kvcm.live under the record logo needs to be changed. We have kvcm.live in our logo, so it appears three times in a row. Perhaps Contact the station or Station Information...?

**Comment by BoscoBonetti** [comment]
Sorry, one more. That ZIP code by itself looks weird. Let's do:

5800 Fulton Ave.
Valley Glen, CA 91401

**Comment by BoscoBonetti** [comment]
Beautiful. Now if we eliminate the spaces between the address lines, but leave one before phone and one before email, I'll [family friendly] off for the day.

**Comment by BoscoBonetti** [comment]
I love how it's coming along -- thank you. My goal is that all of the social media is on the screen without having to scroll down. The first things I'd like to try are:

1. Eliminate the kvcm.live text. It's unnecessary as it appears in two logos in that area. 
2. Eliminate the spaces between the address lines, but leave one before phone and one before email. If that doesn't fix it, eliminate all the spaces from KVCM Radio through email.
