### ISSUE TITLE
Add Sunday Night Oldies to the shows section

### ISSUE THREAD

**Issue by BoscoBonetti** [kvcmlive/website#28]
Content emailed
---
title: "Title"
excerpt: "" # leave this one empty
header:
  teaser: /assets/images/ImageName
sidebar:
  - image: /assets/images/ImageName
  - title: "TimeSlot"
  - title: "Genres"
    text: "GenreList"
---

Show Description
```

**Add any further details here:**
e.g. social media links, playback links, show creator, etc.

**Comment by oofdere** [comment]
closed by c0cfd52
