### ISSUE TITLE
make cover art on shows page square

### ISSUE THREAD

**Issue by oofdere** [kvcmlive/website#3]

**Comment by ravensvoice** [comment]
@oofdere - what do you think of these?

https://www.freecodecamp.org/news/how-to-create-an-image-gallery-with-css-grid-e0f0fd666a5c/

https://medium.com/cloudaper/how-to-create-a-flexible-square-grid-with-css-grid-layout-ea48baf038f3

https://stackoverflow.com/questions/54927180/css-grid-square-layout

**Comment by oofdere** [comment]
That's fine but it still needs to integrate with the framework around it, see https://mmistakes.github.io/minimal-mistakes/docs/configuration/ for the templating docs.

We could try using `feature-row` seeing as we aren't going to have pages for the shows themselves.

**Comment by ravensvoice** [comment]
@oofdere got it! thanks for the link, huge help. So you mind if i just drop the feature-row into the config.yml and then reference it in the shows.md or do you think we will change it enough that i should break it out somewhere else. Let me know how you want to organize stuff

**Comment by oofdere** [comment]
I'd probably do it all in shows.md, you can put it in the info in the header and call it via Liquid.

**Comment by oofdere** [comment]
moved to #7
