### ISSUE TITLE
inconsistent naming for rock and roll cowboy

### ISSUE THREAD

**Issue by oofdere** [kvcmlive/website#32]
Do we make it "Rock and Roll Cowboy" or "Rock N' Roll Cowboy"?

**Comment by BoscoBonetti** [comment]
I Googled last night and he seems to be inconsistent himself between "and" and "&". I think "N'" was Beaton's doing, but I only see "N'" on Twitch, and I can live with it. For everything else, "and" [lower case] please.

**Comment by BoscoBonetti** [comment]
This is closed, but I still see N' on the schedule. Everything but Twitch should be "and" [lower case].

**Comment by BoscoBonetti** [comment]
It's "and" on Saturday and "N'" on Sunday. Sunday's should say "and"

**Comment by oofdere** [comment]
okay, now it should actually be fixed
