### ISSUE TITLE
missing show pages

### ISSUE THREAD

**Issue by oofdere** [kvcmlive/website#35]
Please submit the details for Musicology 101, False Idols, and Stereo Deli.

**Comment by BoscoBonetti** [comment]
*clears throat*

If they'd fuuuuuuuuuuucking submit their stuff to me, I would. :)

**Comment by oofdere** [comment]
nice

**Comment by BoscoBonetti** [comment]
I've:
-had Mr. B send a message to all the DJs
-messaged them all individually myself
-followed up individually myself
-Mr. B followed up with the missing ones

As of now:
-Ozzie is working on his
-I think Alex is working on his, but I don't know.
-Nicole hasn't responded
-KC and Robyn haven't responded

**Comment by BoscoBonetti** [comment]
That wasn't directed at you. I'm super annoyed at people who know I need just a show description and genres, and can't be bothered to send them.

**Comment by oofdere** [comment]
no, you're perfectly justified in your annoyance
