### ISSUE TITLE
disclaimer

### ISSUE THREAD

**Issue by oofdere** [kvcmlive/website#37]
we should add one, please give copy

**Comment by BoscoBonetti** [comment]
Let's talk to Mr. B about this one. I'm not empowered to write legal for anything affiliated with the college.

**Comment by BoscoBonetti** [comment]
We talked about it tonight. He only wants the following somewhere on the About page:

The views expressed on this station do not reflect those of LAVC or the LACCD.

**Comment by oofdere** [comment]
I'll be putting this in the footer for the time being.

**Comment by oofdere** [comment]
41b1f73
