### ISSUE TITLE
overhaul staff page

### ISSUE THREAD

**Issue by oofdere** [kvcmlive/website#40]
we should probably use the infrastructure provided by the author system in Liquid, meaning we need to code the list page itself

**Comment by oofdere** [comment]
working on this at oofdere/website

**Comment by BoscoBonetti** [comment]
Three more pics emailed. Waiting on Alex, Emily, and Tibet.

**Comment by BoscoBonetti** [comment]
All the pics except Tibet's emailed. I don't know what fonts you have available to you (more info in the email), but I'm happy to pop back onto Skype and go through some options together if you like.

**Comment by oofdere** [comment]
done enough I guess, meant to put it in testing but oh well
