### ISSUE TITLE
Add Bites With Trixie to the shows section

### ISSUE THREAD

**Issue by BoscoBonetti** [kvcmlive/website#46]
Content emailed.
---
title: "Title"
excerpt: "" # leave this one empty
header:
  teaser: /assets/images/ImageName
sidebar:
  - image: /assets/images/ImageName
  - title: "TimeSlot"
  - title: "Genres"
    text: "GenreList"
---

Show Description
```

**Add any further details here:**
e.g. social media links, playback links, show creator, etc.

**Comment by oofdere** [comment]
@BoscoBonetti Please fill in the template in the future.
